# Generated by Django 4.1.3 on 2022-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresourceprofile',
            name='image',
            field=models.ImageField(default='static/images/default', upload_to='images/'),
            preserve_default=False,
        ),
    ]
