# Generated by Django 4.1.3 on 2022-11-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_humanresourceprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresourceprofile',
            name='group',
            field=models.CharField(default='HR', max_length=32),
            preserve_default=False,
        ),
    ]
