# Generated by Django 4.1.3 on 2022-11-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_humanresourceprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresourceprofile',
            name='price',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
    ]
