# Generated by Django 4.1.3 on 2022-11-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_humanresourceprofile_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanresourceprofile',
            name='field',
        ),
    ]
