# Generated by Django 4.1.3 on 2022-11-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_humanresourceprofile_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('HR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.humanresourceprofile')),
            ],
        ),
    ]
