# Generated by Django 4.1.3 on 2022-11-15 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_humanresourceprofile_card_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BeReady', '0002_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desceiption', models.TextField()),
                ('appointment_datetime', models.DateTimeField()),
                ('HR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.humanresourceprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
